name = "SigmoidNumbers"
uuid = "f3788140-4e5e-469c-9b73-f9a0e7ddcb53"
author = ["Isaac Yonemoto"]
version = "0.0.0"

[compat]
julia = "0.7, 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[targets]
test = ["Test", "LinearAlgebra"]
